---

- name: solarize terminal
  copy: src=Xresources dest=/home/{{ dev_user }}/.Xresources owner={{ dev_user }} group={{ dev_user}} mode=0644

- name: i3 config
  copy: src=i3/ dest=/home/{{ dev_user }}/.i3 owner={{ dev_user }} group={{ dev_user}} mode=0644
- file: path=/home/{{ dev_user }}/.i3 owner={{ dev_user }} group={{ dev_user }} recurse=yes

- name: dotfiles
  copy: src=gitconfig dest={{ user_home }}/.gitconfig owner={{ dev_user }} group={{ dev_user }}
- copy: src=tmux.conf dest={{ user_home }}/.tmux.conf owner={{ dev_user }} group={{ dev_user }}
- copy: src=powerline/config_files/tmux/default.json dest=/usr/local/lib/python2.7/dist-packages/powerline/config_files/themes/tmux/default.json owner=root group=staff

