---

- name: setup erlang solutions repo
  apt_repository: repo='deb http://packages.erlang-solutions.com/debian {{ ansible_lsb.codename }} contrib'

- name: add Erlang Solutions apt-key
  apt_key: url=http://packages.erlang-solutions.com/debian/erlang_solutions.asc state=present

- name: setup nodejs ppa
  apt_repository: repo='ppa:chris-lea/node.js'

- name: setup webupd8team repo
  apt_repository: repo='ppa:webupd8team/java'

- name: chrome repo
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb stable main'

- name: chrome repo key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: hipchat repo
  apt_repository: repo='deb http://downloads.hipchat.com/linux/apt stable main'
- apt_key: url=https://www.hipchat.com/keys/hipchat-linux.key state=present

- name: install aptitude
  apt: pkg=aptitude

- name: apt-get upgrade
  apt: upgrade=yes update_cache=yes

- name: install git
  apt: pkg=git

- name: install erlang
  apt: pkg=erlang state=latest
- apt: pkg=rebar state=latest

- name: install nodejs
  apt: pkg=nodejs state=latest

- name: Automatically select the Oracle License
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install java
  apt: pkg=oracle-java7-installer state=latest

- name: install ncurses-term
  apt: pkg=ncurses-term

- name: install urxvt
  apt: pkg=rxvt-unicode-256color

- name: install settings daemon
  apt: pkg=gnome-settings-daemon

- name: install i3-wm
  apt: pkg=i3

- name: install tmux
  apt: pkg=tmux

- name: install xclip
  apt: pkg=xclip

- name: install pip
  apt: pkg=python-pip

- name: install curl
  apt: pkg=curl

- name: install build-essential
  apt: pkg=build-essential

- name: aws cli
  pip: name=awscli

- name: install jq
  apt: pkg=jq

- name: install google-chrome
  apt: pkg=google-chrome-stable

- name: install hipchat
  apt: pkg=hipchat

- name: create developer account
  user: name={{ dev_user }} shell=/usr/bin/zsh generate_ssh_key=yes

- name: setup sudoers file
  template: src=sudoers.j2 dest=/etc/sudoers.d/{{ dev_user }} owner=root group=root mode=0440

- name: download vagrant deb
  command: wget -O {{ vagrant_deb_dest }} {{ vagrant_deb_url }} creates={{ vagrant_deb_dest }}

- name: install vagrant
  command: dpkg -i {{ vagrant_deb_dest }}

